[package]
name = "primesq"
version = "0.1.0"
authors = ["chrisr"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primal = "0.3.0"
num-traits = "0.2.14"
num-bigint = "0.3.1"
elapsed = "0.1.2"
ramp = "0.5.9"
